### ISSUE TITLE
Keeps "waiting for location" after enablimg geographic north

### ISSUE THREAD

**Issue by LucaReggiannini** [Kr0oked/Compass#62]
After enabling geographic North the app asks for geolocation permissions. Even if I grant the permission it keeps waiting for a location update forever 

I'm using Lineage for MicroG (Android 13) for POCO F3.

* OS version: `20-20231001-microG-alioth`
* Build number: `lineage_alioth-userdebug 13 TQ3A.230901.001 eng.root.20231001.114356 dev-keys`
* App version is 1.11.4
* GPS and Bluetooth are enabled
* I granted permissions for Mozilla Unified Npl Backend (Mozilla location service)
* tried uninstalling/clearing local data several time

Here is a screen (Italian language):
![Screenshot_20231024-222729_Bussola](https://github.com/Kr0oked/Compass/assets/46603573/9660a5f8-0941-4746-bf67-a39be3d02213)

Is there any other information/thing I can do/provide to try debug the problem?

Btw thanks for making the app.
I really like it and I consider it the main open source compass app.

**Comment by LucaReggiannini** [comment]
Similar to #42

**Comment by Kr0oked** [comment]
There is a chance that this problem is solved with the latest version [1.12.0](https://github.com/Kr0oked/Compass/releases/tag/v.1.12.0). Previously the app only requested your coarse loaction, which gets provided by the network location provider. And it seems this does not work on your system. Now you can allow access to either the fine or the coarse location. The fine location gets provided by the regular GPS provider, which should then hopefully provide a location on your system too.

**Comment by LucaReggiannini** [comment]
Thanks for the reply. Seems like it's still not working but now i get an extra error message after some times:`Location could not be determined. Falling back to magnetic north` and a "Reload location" button. If i tap the button, after some times, every loading text just disappears and i need to reopen the app to make it go again. Is there any other test i can do? Just for information: i see the same permission request as before (no difference for fine/coarse location). If there is no other obvious thing to try, i will make some test on the code

**Comment by Kr0oked** [comment]
If the loading text just disappears then the location was received and the compass shows to true north. So I think it works now.
You can compare the degrees shown with true north enabled with the ones when the setting is not enabled, there should be difference of a few degrees then.
For more specific investigations you can capture the [app logs](https://developer.android.com/tools/logcat). That provides the information which location provider was choosen and which location was received.

**Comment by 0xf0f** [comment]
having this issue as well, version 1.13.0, galaxy s8+ running android pie

**Comment by Kr0oked** [comment]
@tEctutoRIt I'm glad you like the app. The approximate location should already work. When your system supports this, then you should get asked if you want to grant precise or approximate location to the app. Regards
![Screenshot_1716668747](https://github.com/Kr0oked/Compass/assets/5984532/e2fa0f6d-62a5-415e-be5f-27f715217ffc)

**Comment by Kr0oked** [comment]
The location handling was reworked in the latest release https://github.com/Kr0oked/Compass/releases/tag/v2.0.0 . 

Maybe the problems described here are now fixed.
Atleast the approximate location permission should now work properly.

**Comment by tEctutoRIt** [comment]
I can confirm the problems are now fixed in v2.0.0. Thank you!

**Comment by piyushgarg** [comment]
Still same issue in 2.0.1, keeps waiting for location...
Is there anything else I can upload?

[compass-only.log](https://github.com/user-attachments/files/28416958/compass-only.log)
